name: Frontend CI/CD

on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gharsetu-fe:${{ github.sha }}

      - name: Cleanup Docker Images
        run: docker image prune -af

  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: shra-ddha21/GitOps
          token: ${{ secrets.GITOPS_PAT }}
          path: GitOps

      - name: Update Image Tag
        run: |
          cd GitOps
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/gharsetu-fe:${{ github.sha }}|g" frontend/deployment.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update frontend image to ${{ github.sha }}"
          git push
